spring:
  application:
    name: bookai
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1  # 最大连接池大小
      minimum-idle: 1        # 最小空闲连接数
  server:
    port: 8080  # 应用端口
    servlet:
      context-path: /api  # 应用上下文路径
  ai:
    api-key:
